<ul id="sidebarnav">
    <li class="nav-small-cap">APPLICATION</li>
    <li {!! (Request::is('admin') ? 'class="active"' : '') !!}>
        <a href="{{ route('admin.dashboard') }}">
            <i class="fa fa-home"></i><span class="hide-menu">HOME</span>
        </a>
    </li>
    <li {!! (Request::is('admin/setting') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/setting') }}">
            <i class="fa fa-cog"></i><span class="hide-menu">SETTINGS</span>
        </a>
    </li>
    <li {!! (Request::is('admin/destinations') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/destinations') }}">
           <i class="fa fa-location-arrow"></i><span class="hide-menu">DESTINATIONS</span>
        </a>
    </li>
    <li {!! (Request::is('admin/products') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/products') }}">
            <i class="fa fa-th-large"></i><span class="hide-menu">PRODUCTS</span>
        </a>
    </li>
    <li {!! (Request::is('admin/members') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/members') }}">
            <i class="fa fa-users"></i><span class="hide-menu">USERS</span>
        </a>
    </li>
    <li {!! (Request::is('admin/proposals') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/proposals') }}">
            <i class="fa fa-weixin"></i><span class="hide-menu">PROPOSALS</span>
        </a>
    </li>
    <li {!! (Request::is('admin/tags') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/tags') }}">
            <i class="fa fa-tag"></i><span class="hide-menu">TAGS</span>
        </a>
    </li>
    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>

